package game

import (
	"crypto/sha256"
	"fmt"
	"reflect"
	"testing"
)

// Frozen asset-free bytes matching the exact master94245 current-envelope
// SHA before QuickSpells. The producer used that Snapshot field layout and
// verified the already-published hash; no historical fixture is regenerated by
// today's Snapshot encoder. Older native saves must default all four slots.
const preQuickSpellsEnvelope1119 = "H4sIAAAAAAAA/+xZe5BcWVn/ft09/ZhnJpvNJrtBsll2zbISM5NsNuUfFpOeTCZFmrQ9s5ulpvLHSfeZnmtu39veezsz4x+6Iigv" +
	"FXFFRMS3IiCuuCIuiIgrIiIioq6IiCsq4vpaX4h4j/V9597btyfZKlGqqKLmVE3NPd8593s/by+cazVWFh44i3kKtKtVqDuHtXdN" +
	"u35fH547rKLD0YY+3B4Egfaiw6HTG7gqcnzv8Lof9A5dvXPrsecRxXjoW4tAdcVT/XDDj2AeItyC8UVnfd1pD9xoGyVC6WJfeygQ" +
	"Sud8t8OQ4iXfg3kxobZwTTmuuuJq2Y6tqqvag/kOwnRDB23tqWB7JVKR5tenMlDT912YlxH2ZKCzHmPpwLwi/+6yEySw2qLfHvS0" +
	"F4Uw302YSbcNJwwd32Oupuqq11dO18soVlMIzKsJ+9NdQwVXdbCiXd2OdIcvzl7yA7eTQi56bSvPtIAbqt/S0SDwYH6cMHkxcLqO" +
	"p9y6E23D/CRhrKmCaBsxjhIqF9fXNfNcIlRyvI0JJowTKi0dOp2BRoznEtFN5tsKwNjaZceLhGaJ6A7z0gKwb+1yV/X0sdQ4gll0" +
	"a15C9PXm24vA1I7DlxCKqNQ3VD/SAdOtnhk4bsfxusLEea+jt5gC3WK+E0Blbe6UJfwyQgmHiQ6YlwOoMvyKGOkVhAIf3GW+qwDc" +
	"soOn1ApiE/MqojnzyiKw5/rzVzGesQeUO9DiUy9wvI5wEuN+8z1FYG9qnWbgf6Nus6+K1fai1FCOB/MatueG43YCdrHX5p3nkh9c" +
	"ZRnNw4TZoZcFThg5nhbwdT71OsJECnN0KJf2NXXQUx671Y6T8nnPe2GzLs/j5z0vNS3va6v1/HZiZcPvj5znXPcNhJnUzdI7ZcL0" +
	"wiDyz+koB5q4oML8fmrJCcKoofpNny1WYPbt6arT03yjYv06hPlRIjKvMd9bBKZTtbZ02w86osba0DXLhFpD9S9eYZULkqbaFovx" +
	"s5XEGz6rLXljwfP8gde2sVNZ6HSWdeCLrDM2jjNlC7C40GUGifab7yuwd10eOF40d8pqlv39+62/h+rasZ38vpaYZ9pnfqAAlNcS" +
	"t3wdoUB0p/mhArB/9MWhz72BYF7PPvmD7JPXn78+55Pl1CeZzzvMj1zPkNUuKxfmjUTL5ofz6k1P38iBNMRZaTrtaBBoTBLKS452" +
	"O8cZbB/nhNi95seKwGwaMqPZpjCaRVY2/E1Pwsa8yfxEEdiXJYCdWamKygM6SI1cHUr905wVHI+TQogYd40mrR25/4vPmRP3eyor" +
	"CpPM6ZPmp7jIMGeLKlLCwcwIdxNLjqtz+1rdH3iRDo6fHNkdT7y8/0LVE42WlrXqwLyJMN501bYOLjhh4sWytbE7vqhVZ6Ed+cm+" +
	"nNiKCZ9z/SvKXbzErlYmTK4GynF1YCsIZ2sbGSHMe1n9AjbvG6ksHyWiW83PABhfmzshrn1iXpgq41b2pV/L+ZITbVuMVhPvJZg3" +
	"E22YnxVf2nH6ZkIFY3VXhaH4jxUK5q2E0v2eE8G8g1A6H+kezGOE8tn1dY5i825mta9dF+Y9hLFFRwLx7UTUNG9JCVlkltBbCWMo" +
	"pVodW3K2tNSq8rnAH/RDmEcIYy21eWKeoXmER8zPF4CbhtLJGxbrIwTzNqK2+TmuVDsO38ayVVjv4fxxMQsTOH1clC7gE21rrZzl" +
	"iktzbTZTcenk8eT/SYmh55tfSGkIc5bG27kalsW4Icyjtgp3LKpaS7PPs9fazPSLw8zE5ntUMlOMl5tfKgKTjJlVbhG/g3AbxlZ9" +
	"bnaYX6t4i7gqNObubed3953ORFw4JTpsqc0zZ0XHLbU5N3cyBS6ezID35h5P82OK2iKrrLSVq4I5PpnIpLlPQia3Py2pLbVt8tL8" +
	"6Eun5NJU3fci5Xg6WHJVN4m8BGJraLZdVY4bwryTMCWOdsX3r6YvTWeQLKyGIAllyYACSgLUMsVIma/Cg03+Vzv7TQOnb3PWw0R0" +
	"0PwygNrafGajd3KIlYgeNL+S2oiDwdroMfbpZ7CRTb+hwBd14Fyz7j5xSau+753digIlXjFn3pWGi33don631I0M9RAbt0m/mjqi" +
	"CGhfeA8BI9d65teza5xT7LX3McvVlu9HSSXCxKITaPZ/6UMeJ5SlsoQwHyDsSQ+3ba0MYT5EmJQbGeQjRHS7+Y0SMNtT/bUwChyv" +
	"m2nwccIkSzpvfqsE3J67kcazsCcoLY8f4DfM+4nuNr9ZRMG8n2MsrZzcYTJeLlVntiNthb3H/E4BOLQ2ijNj3uL9EMF8kOiU+e0i" +
	"sP+Zbn2QNV9qqmhD0n9WsI+a3ysAB3eQsEqwb36EYD7MxfZ3i8BNN7zy4RHkSQ1nUcm81Py+tBBOtJ21EfLOR7nQls6oUMN8bKRB" +
	"/QSh2lSBcl3twjxBI4movBAEajuE+eRoe/ipLEJDmCfzLd1niOjrzB9wyc9zwZQtJx9j7jMaf5Sj8YQEzx9K8JzKTM83uD4fMn8M" +
	"YGJt/vKwLXuCYB7myHqu+dMCcNtQryldkdMS/gTBfJw1+ydF4OZnuPRx0W2mp6wjPGT+TKifylH/pFCf5Kr65wU+vJyL+U8Rxz0d" +
	"NH8h8tyXHTzJ8kyzt/3NqLeNdjCWnc8QzKeJFsxfpt52o1ufZt/O9YereivigC9JpjJ/TTwv/ZXMS6eFj9MMRBl7iO6JcWcBuHXH" +
	"wMSkkubL9l7ms0SB+Vt2yhvdMZ9lfNXzHe1F3NnZDj2Its8vspNWWaOuzDhPEarcvXj8GheTFeVqbvCeQ5iU52GDxYXtKfN3RWBC" +
	"kDV07wrn+KcIz0bBoq6t6l7fD7jSF3IFZMb2DfUNFag2D5kFRh+pIHK8rowBI5P+6nZfdLd3ZdDvBzoM637QD/UF35cRZrLu9/rK" +
	"c3wZrjht2G6HJ8QzfmdbShY/LDqBRHxDdWWyrzQDf91xNcw/EGpLTncQ6OTOuN0tqbadNO1s8k+EqbRHXh70lAfzr4S9Mgy2/Ei+" +
	"jaz0tW2CJ17g+ZteUqHKwot/FTH2EmazUtbSYeQHthfek0GbgQ61nc9Kl/zAQ4wDhBo/cm1ig7BMdRUEDo+hD7MS7CY9nyaUbSVC" +
	"jD2EvXbTUJEOHOU632xpjvFr24hxqxiba1iMQ4TJps/CJM1gzMM7LZi/L2JUaUVUlpzuRmrCZa3caKPuu4OefOsZbyhPZVuic+Yf" +
	"i8gpcywxUIlQbWll53VWd8MO9lzgncCJ7Nhy1eFm9GkJmH+WgJHvDhy3T/PANEm0af6FS+L1NqqMjAqVlo6cROv5SEh7838faRxE" +
	"2bXz3jXtcRG5XrkcCa82/1YExoXiEMuzEgHLeQHLqYDloYBl221rC7ykWaly8YKvBFatq75qJ9FbtoqW7so+JkN1YoGmDhy/Ywkp" +
	"TyUTj6eSW2KW4Z0ab5dc3w8sGynt8kIUqfZVmM9RmnU/J73OunS8JiZUG37HWXd0gFh0KTZ6sCmFYfzsVl8HTtIdY7zhX9NBJuOo" +
	"36gw830GlDnizy/yvZlM74lS2FeWVXhx07Mv72XuWzrUwTXdlIwRSXIy7zL/wblJLJKTZIKbruVU5danPs/zneqprhYxWZF2u9IP" +
	"tNU/TxDONSvJim77Xie7arfDq1NnXc2Oo9z0ykwGudGttO9JKsIXpNL+Z67Scj37fFJpD5j/EtefT2vFF5L+9QHz39y/irh5E5WG" +
	"FmPeF66EftBP/XC8GfhR+p2MtdDSoRNGim/HIOHEJKFm6THUcmLeEgMcbUJy1BHGUeEgqKs+Yhu8qd1H/HjUeffaXUt3tacDlfKY" +
	"99w91tijF27ssXk/JToYM6uorJ28nIjBaQZVoqMxJsCz9dz85dDpHeMEet7LdDBJiFHGAaLTMcaKKMRiKpTqfmfkg89wOIilcjYD" +
	"R2oH0ZEYtQKwZy3Dn6XVccZeFdwVTh8jh9WRrrjUSAhWLvZ1oJKe9TkxpgrA3rUb8T4tvBOZx2PMFDFaEKaH5bjY8jdFH6lM+WAo" +
	"7QwGNqeNoFJOyyX2LdG+VGvecnnvavmwWJJZ2VVb6W6spbyuhUvkp6yMy67pb9ovz+Us6Im+NsZsEcn9K1ktLaRZWzzB9cUA+4no" +
	"zhg3A5hdmz8tyuHyaz9o8Dli7MNpohMxbhKr7pM+zbLFrimChUnIV20hC21qORTjFvulZj6NTynQ4iadGAeLGC2sucT4NM83UqO5" +
	"ak/lLZaU7apUnr5U4gOcJ5LtsPITfUuM25hIrmJXUapb4b6KUFhuipYbass+2TogvyeorfR5NhdwSTkoEWayGBvCag3Vv99zIsnJ" +
	"RIdjPIsLeY4g8CBfxIvEVlsxns3ZyCbNXBeBKsqr7BY2XusqjOxHtNqyCpNdIfvylA+vzP9rDdX1nGjQSd2ql/SrzNndMe64wU8M" +
	"MqopV9tONsYRoksxbs//ypC7ckRSQ9MPnTTFVL9hoLLeeWphPdJB1iaLHH6v50TS49wV46sLwM1rl3uq7/qqcyzfHcvvO+YpIvPK" +
	"GHcXgZmUfv4XHVSz7/IX2OkK8hWl11Neh9u9R1lBm7b7/xpONRscqDGOEarydWzVfkSpLPnduu9KJ8zPLX9TnieW/O7Zrb4rjee4" +
	"tec9JWCaR3c7CskPOoJdisuRGM8rAXtyF9JycIyvlIni2UfMQwUgLrwY2AccLXJjNLLwv4CUQFQo7DtaOop9iGdftJwe1JL/1eRP" +
	"1vN3vv5/WNX/5/oSsJCtWvFLie3Lvwpf9Ppyc7y7dtfu2l27a3ftrt21u3bX7tpdu2t3fUUtEP1PAAAA//9eZ9fk/y0AAA=="

func TestPreQuickSpellsEnvelopeStillDecodes(t *testing.T) {
	raw := beforeCitySalesEnvelope(t, preQuickSpellsEnvelope1119)
	if h := fmt.Sprintf("%x", sha256.Sum256(raw)); h != "93b8ddb82dbba7f4223e18f822fe33c425688673a9bf0fa001589c8e781250cf" {
		t.Fatalf("published pre-quick envelope changed: %s", h)
	}
	got, label, err := DecodeSave(raw)
	if err != nil {
		t.Fatal(err)
	}
	// This envelope predates 1107 as well as 1119: its World is form72, not
	// today's form73, so the comparison peels the current fixture's World back
	// the same way save_test.go's own form72 controls do.
	want := releasedSaveFixtureSnapshot(t)
	want.World = preCurrentProfileForm1107(t, want.World)
	if label != releasedSaveFixtureLabel || !reflect.DeepEqual(got, want) || got.QuickSpells != [4]uint32{} {
		t.Fatal("published pre-quick envelope changed decoded state")
	}
}
